### ISSUE TITLE
Workflow failed

### ISSUE THREAD

**Issue by annasta13** [lakuapik/jadwalsholatorg#1]
Maret 2024 Workflow failed om. Minta tolong fix ya om.
Terima kasih
Jazakallah khair

Website move to https://www.jadwalsholat.org

**Comment by lakuapik** [comment]
wah terima kasih banyak @annasta13 !

**Comment by annasta13** [comment]
Sama 2 om

**Comment by lakuapik** [comment]
@annasta13 assalamualaikum mas, ternyata upstream jadwalsholat.org berubah lagi, FYI aku barusan update.

**Comment by annasta13** [comment]
Oalah. Iya. Aku ga mantau juga. Soalnya CInya pass.

Thanks sdh dibenerin Mas David
